api_key_env: CROWDIN_API_KEY
project_identifier_env: CROWDIN_PROJECT_ID
base_path: ./redbot/
files:
  - source: cogs/**/locales/messages.pot
    translation: /%original_path%/%locale%.po
  - source: core/**/locales/messages.pot
    translation: /%original_path%/%locale%.po
